# Generated by Django 5.1.5 on 2025-02-08 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_image_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image_link',
        ),
    ]
